version: '3'
services:
  airflow:
    image: apache/airflow:2.9.3
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./:/opt/airflow
    command: bash -lc "pip install -r /opt/airflow/requirements.txt && airflow db init && airflow users create --username admin --password admin --firstname Ajay --lastname Shinde --role Admin --email aj@example.com && airflow scheduler & airflow webserver"
    ports:
      - "8080:8080"
